# Generated by Django 4.2.7 on 2023-12-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_productos_n_producto_alter_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Descripcion',
            field=models.TextField(max_length=2000),
        ),
    ]
