# Generated by Django 4.2.7 on 2023-12-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_productos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Precio',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
